# Generated by Django 4.2.4 on 2023-08-31 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=100)),
                ('client_phone_number', models.CharField(max_length=30)),
                ('client_address', models.TextField()),
                ('client_reg_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_quantity', models.IntegerField()),
                ('product_addition_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total_amount', models.FloatField()),
                ('order_placement_date', models.DateField()),
                ('order_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_store_app.client')),
                ('order_product', models.ManyToManyField(to='online_store_app.product')),
            ],
        ),
    ]
