# Generated by Django 4.2.4 on 2023-09-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_store_app.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_store_app.product')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_product',
            field=models.ManyToManyField(through='online_store_app.OrderProduct', to='online_store_app.product'),
        ),
    ]
