# Generated by Django 4.2.4 on 2023-09-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store_app', '0002_orderproduct_alter_order_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_product',
            field=models.ManyToManyField(to='online_store_app.product'),
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
