# Generated by Django 4.2.4 on 2023-09-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesapp', '0002_author_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
